security:
    basic:
        enabled: false # 是否开启基本的鉴权，默认为true。 true：所有的接口默认都需要被验证，将导致 拦截器[对于 excludePathPatterns()方法失效]
server:
  port: 8052
  context-path: /oauth2-client
---
spring:
  application:
      name: oauth2-client
  profiles:
    active: dev
  thymeleaf:
    cache: false #实现热部署
    mode: LEGACYHTML5 #回避HTML进行严格的检查的配置，当然你需要提前引入nekohtml依赖
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
  mvc:
    static-path-pattern: /static/**

token:
  obtain:
    url: http://localhost:8050/oauth/token #oauth2-server 服务器地址 + oauth/token
swagger2:
  base-package: com.company.controller
  api-title: 接口测试
  version: 0.1.0
debug: true
