security:
    basic:
        enabled: false # 是否开启基本的鉴权，默认为true。 true：所有的接口默认都需要被验证，将导致 拦截器[对于 excludePathPatterns()方法失效]
server:
  port: 8051
  context-path: /oauth2-resouce
---
spring:
  application:
      name: oauth2-resource
  datasource: #数据源的配置
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
  jpa: #jpa的支持：hibernate的相关配置
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    openInView: true
    show_sql: true
    generate-ddl: true #(false)
    hibernate:
        ddl-auto: update #(none)
  redis:
      database: 5
      host: 127.0.0.1
      port: 6379
      pool:
          max-active: 8
          max-wait: 8
          min-idle: 0
          max-idle: 8
  profiles:
    active: dev
  thymeleaf:
    cache: false #实现热部署
    mode: LEGACYHTML5 #回避HTML进行严格的检查的配置，当然你需要提前引入nekohtml依赖
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
  mvc:
    static-path-pattern: /static/**

oauth2:
  resource:
    id: oauth2-resource

swagger2:
  base-package: com.company.controller
  api-title: 接口测试
  version: 0.1.0
